version: "3.8"

services:
  digipin:
    build:
      context: .
      dockerfile: Dockerfile
    image: digipin-api:latest
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: production
      PORT: 5000
    restart: unless-stopped
    networks:
      - digipin-net

networks:
  digipin-net:
    driver: bridge
